### ISSUE TITLE
FontAwesome 5 compatibility

### ISSUE THREAD

**Issue by jyhsu2000** [marvinlabs/laravel-html-font-awesome#6]
Is there any plan for an upgrade to support FontAwesome 5 ?
 
In FontAwesome 4, icon class is always prefixed with `fa`. (e.g. `<i class="fa fa-check"></i>`)
But in FontAwesome 5, even it's support fa, there are still fab, fas, far, fal for different styles. (e.g. `<i class="fas fa-check"></i>`, `<i class="far fa-check"></i>`)

Could you make the helper `fa()` support these styles?
In old version, we can use `fa()->icon('check')` to generate `<i class="fa fa-check"></i>`
Is it possible support some of the following usages to support icon with all styles?
```php
# More helpers
far()->icon('check')
# Style as parameter in fa() (default to solid if no style provided)
fa('s')->icon('check')
fa('solid')->icon('check')
# Style as parameter in icon() (default to solid if no style provided)
fa()->icon('check', 's')
fa()->icon('check', 'solid')
```

https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#changes

**Comment by vpratfr** [comment]
hi,

I would happily welcome a PR.

My preference would go to these syntaxes:

```
# More helpers
far()->icon('check')

# Style as parameter in fa() (default to solid if no style provided)
fa('s')->icon('check')
```

I guess it would make sense to have both. And to have the default style as a configuration parameter.

That way you could simply use the previous code `fa()->check()` and switch to FA5 easily with the style of your choice.
